apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quickstart-ext-conn-traffic
  namespace: cp4i
spec:
  host: quickstart2e-conn.chl.mq.ibm.com
  to:
    kind: Service
    name: quickstart-cp4i-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough